adminUser:
  password: local:seldon-core-test-ci-cluster/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: devext@seldon.io
  token: local:seldon-core-test-ci-cluster/pipelineUser:token
  username: seldondev
prow:
  hmacToken: local:seldon-core-test-ci-cluster/prow:hmacToken
